### ISSUE TITLE
onLoadMoreAsync function calling before end reached.....here is my code

### ISSUE THREAD

**Issue by sukumardv3101** [lexor90/react-native-infinite-scroll#1]
<InfiniteScroll
              onLoadMoreAsync={this.loadMore(newCars)}
              distanceFromEnd={1}
              showsVerticalScrollIndicator={false}
              horizontal={false}
              style={{alignSelf:'stretch'}}>
              {
                this.renderCars()
              }
            </InfiniteScroll>

**Comment by lexor90** [comment]
Hello there @sukumardv3101 
Sorry for the delayed response.

You set a `distanceFromEnd` of `1`, how did you manage to recognize it was actually being called before? Is your initial list larger than the screen?
Otherwise it will be < 1idp thus making the trigger to run.

What react-native version are you using?
Without the full code I cannot reproduce your issue.

**Comment by sukumardv3101** [comment]
Hello there @lexor90 
loadMore = (newCars) => {
     console.log('end reached');
     this.props.actions.loadMoreCars({pageNum: newCars && newCars.meta && newCars.meta.pagination.current_page+1});
  } 

<InfiniteScroll
onLoadMoreAsync={this.loadMore(newCars)}
distanceFromEnd={1}
showsVerticalScrollIndicator={false}
horizontal={false}
style={{alignSelf:'stretch'}}>
{
this.renderCars()
}

initial list having 20 objects.when ever the screen is mounted its automatically calling that 'onLoadMoreAsync'.

**Comment by lexor90** [comment]
Try removing the `alignSelf: stretch` layout prop as it should adapt the container to the viewport size.

Without a fully working example and details about your environment (react native version, platform) it's hard to reproduce.

**Comment by deadcoder0904** [comment]
Hey I did the same mistake ur doing 😸 
`onLoadMoreAsync` must receive a function but not call it & you are calling it

It should be `onLoadMoreAsync={this.loadMore}` inplace of `onLoadMoreAsync={this.loadMore(newCars)}`

Hope it helps 👍

**Comment by lexor90** [comment]
Oh damn, just ignored that. Good spot.

**Comment by tmalahie** [comment]
Thanks for this solution!
The reason why we all made this mistake is because of this code example: https://www.npmjs.com/package/react-native-infinite-scroll.
It would be great if the developer could change it.

**Comment by deadcoder0904** [comment]
Yup I have seen it is wrong in the README itself 😂

**Comment by lexor90** [comment]
@tmalahie @deadcoder0904 thanks for pointing it out.

I didn't update the original README.md file. Going to update it asap

**Comment by lexor90** [comment]
[Update is out on NPM](https://www.npmjs.com/package/react-native-infinite-scroll)

No changes to code, but in order to respect semver I had to update the minor version number (to avoid breaking caching and building systems integrity).

**Comment by lexor90** [comment]
Closed, feel free to re-open should you need to.
