### ISSUE TITLE
How can we scroll to top by clicking on button

### ISSUE THREAD

**Issue by pbhargavi** [lexor90/react-native-infinite-scroll#5]
Hi,

Can you please help me in scroll to top by clicking on button using ref.scrollTo()

**Comment by lexor90** [comment]
Hey there,

What’s the issue? What are you trying to do and what does your code look like?

You are able to use any method or property and pass it down to the native ScrollView component.

**Comment by pbhargavi** [comment]
I am trying to add scroll to top button for scrolling to top but its not working.

Here's the sample i am trying.

`<`InfiniteScroll
        horizontal={false}  //true - if you want in horizontal
        distanceFromEnd={10} ref="maincatScroll"  onLoadMoreAsync={this.loadMore} onScroll={self.onScroll.bind(self)} style={{marginBottom:10}} >
`<`/InfinteScroll>

After infinitescroll i have defined scroll to to button 
`<`TouchableOpacity 
                onPress={this._onscrollPress} style={styles.toTop}><View style={styles.circle}><Text style={styles.circleTxt}>UP</Text></View>`<`/TouchableOpacity>

inside _onscrollPress(){
 this.refs.maincatScroll.scrollTo({x: 0, y: 0, animated: true});
}

its giving  undefined is not a function (evaluating '_this5.refs.maincatScroll.scrollTo({ x: 0, y: 0, animated: true })') error.

**Comment by lexor90** [comment]
You should post some more context about your class. As I can see it is not related to this library, seems more like a reference issue in your class. 

What is your react native version?

I will try to arrange an example by the way, but I will not be able to do so until next week.

**Comment by pbhargavi** [comment]
Thanks for the quick reply.
My react-native version is 0.49.5

**Comment by pbhargavi** [comment]
Also is it possible to scroll continuously in loop i.e. if i have horizontal scroll if it reaches end is it possible to scroll from start automatically

**Comment by lexor90** [comment]
Definitely yes, but you have to manage it on your own depending on your use case and original data structure. In your handler you can do whatever you want to, also pick one element each X, whatever comes to your mind. 

For example, supposing you have an array of images you could track how many images have been returned so far during the scroll, if you have returned the same number of images as your array length, you start returning items from the beginning of the array again. 
If you are using a server side api you could implement it there as well, this would avoid having you to keep track of all of the items being displayed and free some memory. 

It really depends on your requirements, there’s no single answer for every use case.

**Comment by lexor90** [comment]
Not something we do handle (nor we could, tbh) automatically, as you have the power to implement your own logic, in this library though.
